sudo: required
services:
  - docker

before_install:
  - docker build -t zed182/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zed182/react-test npm run test -- --coverage

after_success:
  - docker build -t zed182/multi-client ./client
  - docker build -t zed182/multi-nginx ./nginx
  - docker build -t zed182/multi-server ./server
  - docker build -t zed182/multi-worker ./worker
  # login to docker CLI to push continers
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take all the container images and push to docker hub
  - docker push zed182/multi-client
  - docker push zed182/multi-nginx
  - docker push zed182/multi-server
  - docker push zed182/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-988451896450'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY